# Generated by Django 4.1 on 2022-09-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personas", "0001_initial"),
        ("servicios", "0002_alter_servicio_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("soft_deleted", models.BooleanField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="personas.persona",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="servicios.servicio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
