# Generated by Django 4.1 on 2022-09-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deudas", "0002_initial"),
        ("personas", "0001_initial"),
        ("mediosDePago", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoADeuda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("soft_deleted", models.BooleanField()),
                ("monto", models.FloatField()),
                (
                    "deuda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="deudas.deuda"
                    ),
                ),
                (
                    "medios_de_pagos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="mediosDePago.mediodepago",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
