# Generated by Django 4.1 on 2022-08-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("montosBase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField()),
                ("soft_deleted", models.BooleanField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "amount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="montosBase.montobase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
