# Generated by Django 4.1 on 2022-08-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MontoBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField()),
                ("soft_deleted", models.BooleanField()),
                ("title", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
