# Generated by Django 4.1 on 2022-09-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mediosDePago", "0001_initial"),
        ("conceptos", "0002_alter_concepto_deleted_at"),
        ("personas", "0001_initial"),
        ("pagosUnicos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PagosUnicos",
            new_name="PagoUnico",
        ),
    ]
