# Generated by Django 4.1 on 2022-09-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("soft_deleted", models.BooleanField()),
                ("title", models.CharField(max_length=100)),
                ("late", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
