# Generated by Django 4.1 on 2022-09-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conceptos", "0002_alter_concepto_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("soft_deleted", models.BooleanField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="conceptos.concepto",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
